version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh:ro